name: Build ISO Online
on: [workflow_dispatch]  # Ручной запуск

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Custom ISO
      run: |
        sudo apt-get update
        sudo apt-get install -y genisoimage syslinux squashfs-tools
        # Скачиваем базовую систему
        wget http://mirror.yandex.ru/archlinux/iso/latest/archlinux-x86_64.iso
        # Распаковываем
        mkdir iso-root
        sudo mount -o loop archlinux-x86_64.iso iso-root
        cp -r iso-root/* custom-iso/
        sudo umount iso-root
        
        # Создаём свой конфиг
        echo "Это моя кастомная ОС" > custom-iso/README.txt
        
        # Собираем новый ISO
        genisoimage -o my-custom.iso \
          -b isolinux/isolinux.bin \
          -c isolinux/boot.cat \
          -no-emul-boot -boot-load-size 4 -boot-info-table \
          -J -r -V "MY_OS" custom-iso/
        
    - name: Upload ISO
      uses: actions/upload-artifact@v3
      with:
        name: custom-os-iso
        path: my-custom.iso
